// ==UserScript==
// @name         Quick Links for normal users
// @namespace    *.oneplus.net*
// @version      0.1
// @description  enter something useful
// @author       Mikasa Ackerman aka Kallen
// @match        *.oneplus.net*
// @include        *.oneplus.net*
// @grant        none
// ==/UserScript==

document.getElementsByClassName('i-logo-48')[0].style.backgroundImage = "url('http://i.imgur.com/Mh5L3bR.png')";
document.getElementsByClassName('sidebar')[0].innerHTML = 
    "<div class='sidebar'>"
    + "<a href='/forums/off-topic/create-thread' class='redbutton'><span class='inner'><span class='i-new-post'></span> Create Thread</span></a>"
    + "<div class='section widget-group-no-name widget-container'>"
    + "<div class='secondaryContent widget OnePlus_WidgetCategories_WidgetRenderer_Languages' id='widget-12'>"
    + "<h3>"
    + "<span class='i-world'></span> Quick Links"
    + "</h3>"
    + "<ul class='xenforo-list-2cols'>"
    + "<li><a href='/account/signature/'>Edit Signature</a></li>"
    + "<li><a href='https://account.oneplus.net/invite/overview'>View Invites</a></li>"
    + "<li><a href='/conversations/add'>Start PM</a></li>"
    + "<li><a href='/account/ignored'>Blocked People</a></li>"
    + "<li><a href='/account/following'>Following</a></li>"
    + "<li><a href='/watched/threads'>Watched Threads</a></li>"
    + "<li><a href='/account/likes'>Likes Received</a></li>"
    + "</ul>"
    + "<div class='clearfix' style='clear:left'></div>"
    + "</div>"
    + "</div>"
    + "<div class='section widget-group-no-name widget-container'>"
    + "<div class='secondaryContent widget OnePlus_WidgetCategories_WidgetRenderer_Languages' id='widget-12'>"
    + "<h3>"
    + "<span class='i-world'></span> Favorite Threads"
    + "</h3>"
    + "<ul class='xenforo-list-2cols'>"
    + "<li><a href='/threads/the-fellowship.65289'>The Fellowship</a></li>"
    + "</ul>"
    + "<div class='clearfix' style='clear:left'></div>"
    + "</div>"
    + "</div>"
    + "<div class='section widget-group-no-name widget-container'>"
    + "<div class='secondaryContent widget OnePlus_WidgetCategories_WidgetRenderer_Languages' id='widget-12'>"
    + "<h3>"
    + "<span class='i-world'></span> Custom Tools"
    + "</h3>"
    + "<ul class='xenforo-list-2cols'>"
    + "<li><a href='/forums/dansk/'>Coming Soon</a></li>"
    + "</ul>"
    + "<div class='clearfix' style='clear:left'></div>"
    + "</div>"
    + "</div>"
    + "<div class='section widget-group-no-name widget-container'>"
    + "<div class='secondaryContent widget OnePlus_WidgetCategories_WidgetRenderer_Categories' id='widget-11'>"
    + "<h3>"
    + "<span class='i-world'></span>All Categories"
    + "</h3>"
    + "<ul class='xenforo-list-2cols'>"
    + "<li><a href='/forums/announcements/'>Announcements</a></li>"
    + "<li><a href='/forums/the-one/'>The One</a></li>"
    + "<li><a href='/forums/cyanogenmod-11s/'>CyanogenMod 11S</a></li>"
    + "<li><a href='/forums/dev-roms/'>Development</a></li>"
    + "<li><a href='/forums/off-topic/'>Off Topic</a></li>"
    + "<li><a href='/forums/tech-support/'>Tech Support</a></li>"
    + "<li><a href='/forums/accessories/'>Accessories</a></li>"
    + "<li><a href='/forums/introduce-yourself/'>Introduce Yourself</a></li>"
    + "<li><a href='/forums/tech-talk/'>Tech Talk</a></li>"
    + "<li><a href='/forums/fan-gatherings/'>Fan Gatherings</a></li>"
    + "<li><a href='/forums/invites/'>Invites</a></li>"
    + "</ul>"
    + "<div class='clearfix' style='clear:left'></div>"
    + "<script>"
    + "    $('#create-thread-button').on('click', function(e) {"
    + "        e.preventDefault();"
    + "        $('#newthread-category').toggle();"
    + "    });"
    + "    $('#create-thread-close').on('click', function(e) {"
    + "        e.preventDefault();"
    + "        $('#newthread-category').toggle();"
    + "    });"
    + "    </script>"
    + "</div>"
    + "</div>"
    + "<div class='section widget-group-no-name widget-container'>"
    + "<div class='secondaryContent widget OnePlus_WidgetCategories_WidgetRenderer_Stats' id='widget-4'>"
    + "<h3>"
    + "<span class='i-stats'></span> Forum Statistics"
    + "</h3>"
    + "<div class='pairsJustified'>"
    + "<dl class='discussionCount'><dt>Discussions:</dt>"
    + "<dd>114,201</dd></dl>"
    + "<dl class='messageCount'><dt>Messages:</dt>"
    + "<dd>5,780,704</dd></dl>"
    + "<dl class='memberCount'><dt>Members:</dt>"
    + "<dd>269,363</dd></dl>"
    + "<dl><dt>Latest Member:</dt>"
    + "<dd><a href='members/pie004.270323/' class='username' dir='auto'>pie004</a></dd></dl>"
    + "<dl><dt>Online:</dt>"
    + "<dd><a href='/online/?type=registered'>2,703</a></dd></dl>"
    + " "
    + "</div>"
    + "</div>"
    + "</div>"